### ISSUE TITLE
add some missing paper and code

### ISSUE THREAD

**Issue by heyblackC** [ZigeW/data_management_LLM#1]
Hello, thank you for your great share!

I notice your README miss some papers. Please have a look at the following content and add them to your collection.

MoDS: Model-oriented Data Selection for Instruction Tuning (https://arxiv.org/abs/2311.15653, https://github.com/CASIA-LM/MoDS)

Superfiltering: Weak-to-Strong Data Filtering for Fast Instruction-Tuning (https://arxiv.org/abs/2402.00530)
 
about the paper "Instruction mining: High-quality instruction data selection for large language models" , you can find its code here (attached in the supplementary material in OpenReview):
https://openreview.net/attachment?id=kce6LTZ5vY&name=supplementary_material
https://openreview.net/forum?id=kce6LTZ5vY

**Comment by ZigeW** [comment]
Thanks for your kind information! The collection is updated.

**Comment by heyblackC** [comment]
Many thanks!

**Comment by heyblackC** [comment]
Many thanks!
